config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :companies
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "companies#index"

  post 'create_contct', to: "contacts#create_contact"
  post 'connect_user', to: "contacts#connect_user"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :contacts, dependent: :delete_all
end

app/models/connect.rb
class Connect < ApplicationRecord
  belongs_to :connector, class_name: 'Contact'
  belongs_to :connectee, class_name: 'Contact'
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :company

  has_many :followed_contacts, foreign_key: :connector_id, class_name: 'Connect'
  has_many :connectees, through: :followed_contacts

  has_many :following_contacts, foreign_key: :connectee_id, class_name: 'Connect'
  has_many :connectors, through: :following_contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @contacts = Contact.all.where(company_id: params[:id])
    @company_contact_list = @contacts.pluck(:name,:id)

  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:name, :abn, :company_id)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @companies = Company.all.pluck(:name, :id)
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to controller: 'companies', action: 'show', id: contact_params[:company_id], notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_contact
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to controller: 'companies', action: 'show', id: contact_params[:company_id], notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def connect_user
    @connection = Connect.new(connector_id: params[:id], connectee_id: params[:new_contact_id])
    respond_to do |format|
      if @connection.save
        format.html { redirect_to controller: 'companies', action: 'show', id: contact_params[:company_id], notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @connection }
      else
        format.html { render :new }
        format.json { render json: @connection.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_params
      params.permit(:name, :company_id, :new_contact_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
        <% company.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="w-full max-w-xs">
  <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="mb-4">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
        Name
      </label>
      <%= form.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="mb-6">
      <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
      ABN
      </label>
      <%= form.text_field :abn, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>

    </div>
    <div class="flex items-center justify-between">

    <%= form.submit "Create Company", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  </form>
</div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<div class="flex mb-4 h-full">
  <div class="w-1/5 h-full">
    <div class="text-center text-xl font-bold pt-4">All Companies</div>
    <p class="mt-4 text-center">
      View your companies <br>or<br> create a new company
    </p>
    <div class="flex h-full mt-4 items-center ">
      <%= link_to 'Back', companies_path, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-8 mr-4"  %>
    </div>

</div>
 <div class="w-3/5 h-full">


<table class="table-fixed w-full">
  <thead>
    <tr>
      <th>Company</th>
      <th>Abn</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @companies.empty? %>
      <tr>
        <td colspan="3" class="font-bold text-m">No Companies exsist. Create a new company - <%= link_to 'Create first company', new_company_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %></td>
      </tr>

    <% end %>

    <% @companies.each do |company| %>
      <tr class="h-full mt-6">
        <td class="ml-6 font-bold text-xl"><%= company.name %></td>
        <td class="text-center h-full mt-6"><%= company.abn %></td>
        <td class="h-12 mt-6">
        <%= link_to 'Show', company, class:"bg-blue-500 hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
        <%= link_to 'Edit', edit_company_path(company), class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
        <%= link_to 'Delete', company, method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-transparent hover:bg-red-700 text-white font-bold py-2 px-4 border border-red-700 rounded"  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
 </div>
<br>

 <div class="w-1/5 h-full">
   <div class="m-8">

     <%= link_to 'New Company', new_company_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
   </div>
</div>

</div>

app/views/companies/new.html.erb
<div class="flex mb-8">
  <div class="w-1/5">
    <div class="my-8">
      <%= link_to 'Back', companies_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
    </div>
  </div>
  <div class="w-3/5">
    <div class="font-bold text-2xl my-10 ">Create New Company</div>

    <%= render 'form', company: @company %>
  </div>
</div>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>
<div class="flex mb-6 h-full">
  <div class="w-1/5 h-full">
    <div class="text-center text-xl font-bold pt-4">
      <%= @company.name %> Contacts
    </div>
    <p class="mt-4 text-center">
    Company ABN:  <%= @company.abn %>
    </p>
    <div class="flex h-full mt-4 items-center ">
      <%= link_to 'Back', companies_path, class:"bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-8 mr-4"  %>
    </div>
  </div>
  <div class="w-3/5 h-full mt-2">
    <table class="table-fixed w-full mt-6">
      <thead>
        <tr>
            <div class="mx-auto text-center mb-4 mt-6 text-3xl text-bold">
              Company Contacts
            </div>
          <th class="w-1/4 px-4 py-2">Contact Name</th>
          <th class="w-2/4 px-4 py-2">Connected To</th>
          <th class="w-1/4 px-4 py-2">Connect Contact</th>
        </tr>
      </thead>
      <tbody class="mb-8">
        <% @contacts.each do |contact| %>
          <tr>
            <td class="border px-4 py-2"><%= contact.name %></td>
            <td class="border px-4 py-2">
              <ul class="list-inside">
                <% if contact.connectees.empty? %>
                  <li>No Connected Users</li>
                <% else %>
                  <% contact.connectees.each do |connection| %>
                  <li><%= connection.name %></li>
                  <% end %>
                <% end %>
              </ul>
            </td>
            <td class="border px-4 py-2">
              <%= form_with url: connect_user_path do %>
                <%= select_tag(:new_contact_id, options_for_select(@company_contact_list)) %>
                <%= hidden_field_tag(:id, contact.id) %>
                <%= hidden_field_tag(:company_id, contact.company_id) %>
                <%= submit_tag("Create") %>
                <% end %>
            </td>
          </tr>
          <% end %>
      </tbody>
    </table>
    <%= link_to "Add New Contact", new_contact_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 hover:border-transparent rounded" %>
  </div>
  <div class="w-1/5  h-full mx-auto" >
    <div class="flex h-full mt-4 items-center ">
    <%= link_to 'Edit', edit_company_path(@company), class:"bg-green-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-12 ml-8" %>
    </div>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/_new_form.html.erb
  <%= form_with(model: contact, local: true) do |form| %>
    <% if contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

        <ul>
          <% contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="w-full max-w-xs">
      <form class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        <div class="mb-4">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="username">
            Name
          </label>
          <%= text_field_tag(:name, nil, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline") %>
        </div>
        <div class="mb-6">
          <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
            Company
          </label>
          <%= select_tag(:company_id, options_for_select(@companies), class: "shadow appearance-none border-blue-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline") %>
        </div>
        <div class="flex items-center justify-between">

        <%= form.submit "Create Contact", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
        </div>
      </form>
    </div>
  <% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Company</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.company.name %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>

app/views/contacts/new.html.erb
<div class="flex mb-8">
  <div class="w-1/5">
    <div class="my-8">
      <%= link_to 'Back', contacts_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
    </div>
  </div>
  <div class="w-3/5">
    <div class="font-bold text-2xl my-10 ">Create New Contact</div>

    <%= render 'new_form', contact: @contact %>
  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="flex mb-8">
  <div class="w-1/5">
    <div class="my-8">
      <%= link_to 'Back', contacts_path, class: "bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white py-2 px-4 border border-blue-500 hover:border-transparent rounded" %>
    </div>
  </div>
  <div class="w-3/5">
    <div class="font-bold text-2xl my-10 ">Contact</div>
    <p>
      <strong>Name:</strong>
      <%= @contact.name %>
    </p>
    <p>
      <strong>Company:</strong>
      <%= @contact.company_id %>
    </p>
  </div>
  <div class="w-1/5">
    <div class="my-8">
    <%= link_to 'Edit', edit_contact_path(@contact), class: "bg-transparent hover:bg-green-500 text-green-700 font-semibold hover:text-white py-2 px-4 border border-green-500 hover:border-transparent rounded" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyContacts</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="flex items-center justify-between flex-wrap bg-teal-500 p-6">
      <div class="flex items-center flex-shrink-0 text-white mr-6">
        <span class="font-semibold text-xl tracking-tight">Company Contact</span>
      </div>
      <div class="block lg:hidden">
        <button class="flex items-center px-3 py-2 border rounded text-teal-200 border-teal-400 hover:text-white hover:border-white">
          <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
        </button>
      </div>
      <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
        <div class="text-sm lg:flex-grow">
          <%= link_to "Companies", companies_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200"  %>
          <%= link_to "Contacts", contacts_path, class: "block mt-4 lg:inline-block lg:mt-0 text-teal-200"  %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>